# action.yml
name: 'OpenTTD CDN Version Scraper'
description: 'Query the latest version of OpenTTD'
inputs:
  channel:
    description: 'Channel to query'
    required: true
    default: 'stable'
outputs:
  version:
    description: 'The latest version corresponding to the given channel'
  semver_major:
    description: 'The major semantic version for this release, if available'
  semver_minor:
    description: 'The minor semantic version for this release, if available'
  semver_patch:
    description: 'The patch semantic version for this release, if available'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/ropenttd/cdn_version_scraper:sha-ccc1941'
  args:
  - ${{ inputs.channel }}
  env:
    GITHUB_ACTION: "true"
