name: Build

on:
  push:
    branches:
      - master

jobs:
  cri:
    strategy:
      matrix:
        arch:
          - os: ubuntu-24.04
            name: linux/amd64
            label: linux-amd64
          - os: ubuntu-24.04-arm
            name: linux/arm64
            label: linux-arm64
    runs-on: ${{ matrix.arch.os }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Generate CRI metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/cdn_version_scraper
          labels: |
            org.opencontainers.image.title=OpenTTD CDN Version Scraper
            org.opencontainers.image.description=A basic utility for scraping current version information from the OpenTTD project.
            org.opencontainers.image.url=https://github.com/ropenttd/cdn_version_scraper
            org.opencontainers.image.source=https://github.com/ropenttd/cdn_version_scraper
            org.opencontainers.image.vendor=Reddit OpenTTD
          tags: |
            type=sha,format=long,suffix=-${{ matrix.arch.label }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCI
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.arch.name }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  release-bundle-manifest:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: cri

    steps:
      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Create and push manifest
        uses: Noelware/docker-manifest-action@v0.4.2
        with:
          inputs: $GHCR_REPO:latest
          images: $GHCR_REPO:sha-${{ github.sha }}-linux-amd64,$GHCR_REPO:sha-${{ github.sha }}-linux-arm64,$GHCR_REPO:sha-${{ github.sha }}-linux-arm-v6,$GHCR_REPO:sha-${{ github.sha }}-linux-arm-v7
          push: true