name: Build

on:
  push:
    branches:
      - master

jobs:
  cri:
    strategy:
      matrix:
        arch:
          - os: ubuntu-24.04
            name: linux/amd64
          - os: ubuntu-24.04-arm
            name: linux/arm64
    runs-on: ${{ matrix.arch.os }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Generate CRI metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/cdn_version_scraper
          labels: |
            org.opencontainers.image.title=OpenTTD CDN Version Scraper
            org.opencontainers.image.description=A basic utility for scraping current version information from the OpenTTD project.
            org.opencontainers.image.url=https://github.com/ropenttd/cdn_version_scraper
            org.opencontainers.image.source=https://github.com/ropenttd/cdn_version_scraper
            org.opencontainers.image.vendor=Reddit OpenTTD
          tags: |
            latest
            type=sha
      
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCI
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.arch.name }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
